### ISSUE TITLE
mktemp --suffix is not supported on macOS

### ISSUE THREAD

**Issue by srubben** [mickeynp/ezf#1]
I was trying this out on macOS, but I had to switch to the GNU Coreutils version of mktemp to make it work because the default mktemp does not support --suffix.

The macOS version supports -t (prefix) instead of --suffix. So something like this work on both macOS and linux:
```mktemp -t emacs.XXXXXXX```

**Comment by mickeynp** [comment]
Fixed. Thanks for the bug report.
